### ISSUE TITLE
Rest client enable cross partition

### ISSUE THREAD

**Issue by mario-imperato** [btnguyen2k/gocosmos#16] opened 2022-11-29 14:51 UTC
Hi there, I'm reaching you to ask about the ability to do cross-partition on the rest client. On my installation I'm experiencing an issue and I'm not able to do real cross-partition. On Ms documentation is reported that the header to be used is X-Ms-Documentdb-Query-EnableCrossPartition (as the matter of fact one do you use in restclient.go line: 575. With this setting (set to true) I'm experiencing problems. Reading ms https://learn.microsoft.com/it-it/rest/api/cosmos-db/querying-cosmosdb-resources-using-the-rest-api I noticed that the proposed example suggests the use of a different header (x-ms-query-enable-crosspartition: True). 
Do you have an idea if MS people changed this stuff underneath and which is the correct one?
Thank you
M.

**Comment by mario-imperato** [comment] 2022-11-29 17:27
May be this issue is linked to this statement: `req.Header.Set("X-Ms-Documentdb-PartitionkeyRangeid", resultPkranges.Pkranges[0].Id)` and a note that says: // TODO: what if there are 2 pk ranges or more?

**Comment by btnguyen2k** [comment] 2022-11-30 02:29
Hi @mario-imperato, what was the issue/error you encountered? Can you give more details?
The document says the header is `X-Ms-Documentdb-Query-EnableCrossPartition` (case is insensitive). So everything is working ok from my side.

**Comment by mario-imperato** [comment] 2022-11-30 07:47
Hi @btnguyen2k. Hope that this note might shed some light on this.

We tried query-ing a cosmosdb installation in a single and multi (physical) partition. The query used is __cross partition__ in that it doesn't contains the p-key as to speak. The query uses the rest client, issues the query, set the page size and browse the data page after page using continuation token. In a single partition it works ok. In a multi partition it doesn't extract all the relevant data but seems to extract only a subset of the data. Difficult to tell if the subset is from a single partition or not since the partition key used is the id of the document (sort of uuid). Let's say we got 90K docs out of many more that are targeted by the query.... So, the problem might be in 3 places as to speak. 

1. **we got a bug in our code** (can be but actually the code is the same. the flag CrossPartitionEnabled is set to true and there is really no difference from single partition case)
2. **there is some issue in your rest client**. we looked into the headers you were using in the call when the CrossPartitionEnabled is set to true. I noticed two points. 
You set the `X-Ms-Documentdb-Query-EnableCrossPartition` and we found that Ms documents here and there reference another form of the same header (a change over time.... dunno), 
and when you do the `resultPkranges = c.GetPkranges(query.DbName, query.CollName)` and you set `if len(resultPkranges.Pkranges) > 0 { ....` (on line 576). On line 577 I noticed also that there is a TODO comment.... `// TODO: what if there are 2 pk ranges or more?` and actually in the code you use the 0 element of the array (note: the resultPkranges returns an array of 2 items in our case (see the json below)). 
3. **the ms folks have a problem or cosmosdb has significative problems** in managing this stuff (I believe that some truth is in this one IMHO). This is quite the most problematic of the three.... as you might imagine...

```
{
  "PartitionKeyRanges": [
    {
      "id": "3",
      "maxExclusive": "05C1E0",
      "minInclusive": "",
      "_rid": "1KkeALHpWkYFAAAAAAAAUA==",
      "_ts": 1669654642,
      "_self": "dbs/1KkeAA==/colls/1KkeALHpWkY=/pkranges/1KkeALHpWkYFAAAAAAAAUA==/",
      "_etag": "\"0000f405-0000-0d00-0000-6384e8720000\""
    },
    {
      "id": "4",
      "maxExclusive": "FF",
      "minInclusive": "05C1E0",
      "_rid": "1KkeALHpWkYGAAAAAAAAUA==",
      "_ts": 1669654642,
      "_self": "dbs/1KkeAA==/colls/1KkeALHpWkY=/pkranges/1KkeALHpWkYGAAAAAAAAUA==/",
      "_etag": "\"0000f505-0000-0d00-0000-6384e8720000\""
    }
  ],
  "_count": 2
}
```

What I did. I forked the code and made a tiny modification on the rest client. 
I made **TWO** iterations:

**First: I added the following header without removing the current.**

```
req.Header.Set("x-ms-query-enable-crosspartition", "True")
```

This run gave exactly the same results as before.... 

**Second: commented out the section on  `X-Ms-Documentdb-PartitionkeyRangeid`**

```
/*
	req.Header.Set("X-Ms-Documentdb-Query-ParallelizeCrossPartitionQuery", "true")
	req.Header.Set("X-Ms-Documentdb-PartitionkeyRangeid", resultPkranges.Pkranges[0].Id)
*/
```

Apparently, in the second iteration the client surpassed the number of previously retrieved documents (we ran this yesterday night 8PM GMT and don't have the final result). 
Later in this morning I will report more details on this second run.
M.

**Comment by mario-imperato** [comment] 2022-11-30 09:26
Apparently leaving out the setting of the `X-Ms-Documentdb-PartitionkeyRangeid` (we left out both but the guess is more on the second than on the first) the number of retrieved documents match the expected value.
M.

**Comment by btnguyen2k** [comment] 2022-11-30 09:28
Hi @mario-imperato, thanks for the info. I can reproduce the error, and found where the issue is. Currently working on a fix. Cheers.

**Comment by btnguyen2k** [comment] 2022-12-02 05:24
Hi @mario-imperato, issue with cross-partition queries has been partially fixed in v0.1.7.
There are still some known issues which will be addressed soon:
- Cross-partition queries with ORDER BY: the returned items are currently not in correct order.
- Cross-partition queries with GROUP BY: the returned items are currently not correctly grouped.

**Comment by mario-imperato** [comment] 2022-12-02 10:00
Thank you @btnguyen2k we will switch to the new version and keep you informed of any further issue.

**Comment by mario-imperato** [comment] 2022-12-02 13:07
By replacing the `test` version with the released version we got an error that's logged in this way.

```
{"level":"error","error":"Post \"[https://cgectngcosmos01azwe.documents.azure.com:443/dbs/gect-db-cert/colls/DocumentsContainer/docs\":](https://cgectngcosmos01azwe.documents.azure.com/dbs/gect-db-cert/colls/DocumentsContainer/docs/)
net/http: HTTP/1.x transport connection broken: http: ContentLength=540
with Body length 0","time":"2022-12-02T12:34:40.132+01:00"}
```

Looking at the code, I can see two type of modifications:

- One is cosmetic in some sense (you replaced const with the header names in the code). Actually you changed the casing that in principle should not matter...
- The other is that you do the querying by cycling over the ranges and doing the query one by one. In our setup, think the collection are enabled for cross partition this doesn't seem a problem, and in fact we were able to querying by leaving out the range id heather altoghether. On the other side this approach rises a question about the `MaxItemCount` that might now be interpreted as a `MaxItemCount` for each range-id. 

Let me know what do you think of the error (quite generic as the matter of fact) and what could you suggest for further investigation.

**Comment by btnguyen2k** [comment] 2022-12-02 13:20
Hi @mario-imperato , the logged error seems to come from your own error logging func, doesn’t it? Or is it the origional error from the rest api client?
Also, can you try again with the Azure CosmosDB Emulation (the one that can run locally for dev purpose).

Cheers,

**Comment by mario-imperato** [comment] 2022-12-02 13:25
Yes the error comes out from my logging out of your code. Don't know exactly what is going on inside....
COuld you just shed some light why do you execute a query on each rangeId in the cross partition case? From discussions on the web is not clear what is provided by rest-api and whats not and why you, the remote client should do this kind of working... In principle, iif you have to do this working whar is the meaning of the cross-partition header in the first place?

**Comment by mario-imperato** [comment] 2022-12-02 14:15
What we got so far.

The call `GetPkranges` always returns good. Below the json in our case. 

```
{
  "PartitionKeyRanges": [
    {
      "id": "3",
      "maxExclusive": "05C1E0",
      "minInclusive": "",
      "_rid": "1KkeALHpWkYFAAAAAAAAUA==",
      "_ts": 1669654642,
      "_self": "dbs/1KkeAA==/colls/1KkeALHpWkY=/pkranges/1KkeALHpWkYFAAAAAAAAUA==/",
      "_etag": "\"0000f405-0000-0d00-0000-6384e8720000\""
    },
    {
      "id": "4",
      "maxExclusive": "FF",
      "minInclusive": "05C1E0",
      "_rid": "1KkeALHpWkYGAAAAAAAAUA==",
      "_ts": 1669654642,
      "_self": "dbs/1KkeAA==/colls/1KkeALHpWkY=/pkranges/1KkeALHpWkYGAAAAAAAAUA==/",
      "_etag": "\"0000f505-0000-0d00-0000-6384e8720000\""
    }
  ],
  "_count": 2
}
```

Next when the first rangeId is queried there are two cases:

1. no documents are matched by the query. it tries with the second rangeid and finishes.
2. documents are matched and you get an error that is logged that way

```
"Post \"https://cgectngcosmos01azwe.documents.azure.com:443/dbs/gect-db-cert/colls/DocumentsContainer/docs\": net/http: HTTP/1.x transport connection broken: http: ContentLength=540 with Body length 0"
```

it got a content-length but apparently no body or no body could be read.

**Comment by btnguyen2k** [comment] 2022-12-02 15:13
Hi @mario-imperato , thanks for the info. A fix is on the way.

**Comment by mario-imperato** [comment] 2022-12-02 19:34
Hi @btnguyen2k I've been digging into the code. 
I share with you my personal opinion of the current issue. Hope you'll find some use of my considerations and my english is good enough to make them understandable.

My guess is that the problem comes out from the re-use of the http.Request during your loops in the ranges. As the matter of fact what happens is that when you do a query by pkrangeid you loop over the query using the continuation token. In this re-use the http.Request has consumed the body and the error happens. In our case we asked for a document count of 100 and the code found two ranges: id=3, id=4. It starts doing query on id=3. First iteration goes good and found 100 docs. Next, it started a second iteration that wen bad with the error. To avoid the error is likely that the request has to be somewhat re-initialized as to speak.

Assuming that this might solve the issue, this raises a bigger issue on the pattern used in handling cross partitions. In your loop over a rangeId you keep extracting data until the continuation token is good. You don't return soon to the caller with the continuation token (the way you do in a NON cross partition query.......) This means that if that range has 100K docs you keep in memory 100K docs plus all the docs in the other partitions..... a number difficult to manage.  On the other side 

1. if you execute one single iteration on each range-id what continuation token will you provide back to the caller? 
2. And if you have four partitions and asked for 100 Max-Item-Count you return 400 docs a time?

This gets confusing to me. But I think in the multi partition scenario there are two possible approaches.

1. put the crosspartition to true (enabling cross-partition queries on cosmos... big bucks) and leave alone the range id
2. provide a way for the caller (thats me who calls the gocosmos) to specify the rangeId in order to directly address the rangeid and handle the continuation token outside. Me, the caller, after 100docs will make some use of these docs and discard them not having 1Milion documents to pile up in memory.

At the moment, in my temporary fork I'm just bypassing the rangeId by using this type of hack. It's running...
```
if query.CrossPartitionEnabled {
   req.Header.Set(restApiHeaderEnableCrossPartitionQuery, "true")
   req.Header.Set(restApiHeaderParallelizeCrossPartitionQuery, "true")
   // return c.queryDocumentsCrossPartitions(query, req)
}
```

**Comment by mario-imperato** [comment] 2022-12-02 21:20
As a minor update. In a run the query took out of cosmos sort of 832497 documents with the simple hack posted in the message above.
M.

**Comment by btnguyen2k** [comment] 2022-12-05 01:30
@mario-imperato v0.1.8 has been out to fix some of the issues with cross-partition queries.
Please be noted that queries with ORDER BY or GROUP BY are still not working properly when there are more than 1 physical partition. That issue will be addressed in latter releases.
Thank you very much for support and testing.

Best regards,
Thanh

**Comment by btnguyen2k** [comment] 2023-03-14 10:18
@mario-imperato v0.2.0 has been out to further address cross-partition queries. Since there has been no update from you for quite awhile. I'll be closing this issue for now. Feel free to comment/reopen if needed.

**Closed by btnguyen2k** 2023-03-14 10:18 UTC

**Comment by mario-imperato** [comment] 2023-03-14 10:56
Thank you. I'll check. At the moment we have been using the 1.1.8. I'll upgrade to the new release. 
M.
